// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Api.Data;

namespace backend.Api.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190424013234_CreateUserTable")]
    partial class CreateUserTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(64);

                    b.Property<int>("IsVerifyEmail")
                        .HasColumnName("is_verify_email");

                    b.Property<int>("IsVerifyPhone")
                        .HasColumnName("is_verify_phone");

                    b.Property<string>("NickName")
                        .HasColumnName("nick_name")
                        .HasMaxLength(64);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasMaxLength(64);

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(64);

                    b.Property<string>("UserName")
                        .HasColumnName("user_name")
                        .HasMaxLength(64);

                    b.Property<int>("UserRole")
                        .HasColumnName("user_role");

                    b.HasKey("Id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
